---
- name: install zabbix apt repository
  apt:
    deb: '{{ zabbix_repo }}'
- name: install prerequisites
  apt:
    name: '{{ apt_packages }}'
    update_cache: yes
  notify: secure mariadb
- name: disable the default apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache
- name: open firewall to load balancer
  ufw:
    rule: allow
    from_ip: '{{ ufw_fromip }}'
    name: Apache
  when: 'ufw_fromip is defined'
- name: open firewall to active checks
  ufw:
    rule: allow
    port: '10051'
    proto: tcp
