---
- name: install prerequisite software
  apt:
    name:
      - apt-transport-https
      - gpg                     # Required for apt_key module
      - i965-va-driver          # Drivers for GPU
      - intel-media-va-driver-non-free   # Drivers for GPU
      - vainfo                  # Driver verification
- name: download jellyfin gpg key
  get_url:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    dest: /usr/share/keyrings/jellyfin_team.gpg.key
- name: configure jellyfin repository
  apt_repository:
    filename: jellyfin
    repo: 'deb [signed-by=/usr/share/keyrings/jellyfin_team.gpg.key arch=amd64] https://repo.jellyfin.org/ubuntu focal main'
- name: install jellyfin
  apt:
    name: jellyfin
- name: add jellyfin user to video group for hw acceleration
  user:
    name: jellyfin
    groups: video
    append: yes
- name: open firewall to load balancer
  ufw:
    rule: allow
    from_ip: '{{ ufw_fromip }}'
    port: '8096'
    proto: 'tcp'
  when: 'ufw_fromip is defined'
