#!/usr/bin/env bash
cd /etc/letsencrypt/live
for i in *; do
	if [ "$i" != "README" ]; then
		/usr/bin/cat "/etc/letsencrypt/live/$i/fullchain.pem" "/etc/letsencrypt/live/$i/privkey.pem" > "/etc/haproxy/ssl/$i.pem"
	fi
done
/usr/bin/systemctl reload haproxy.service
