---
- name: install prerequisite software
  apt:
    name:
      - gpg                     # Required for apt_key module
      - i965-va-driver          # Drivers for GPU
      - intel-media-va-driver-non-free   # Drivers for GPU
      - vainfo                  # Driver verification
      - wget                    # Plex post-install script wants wget
- name: download plex gpg key
  get_url:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    dest: /usr/share/keyrings/PlexSign.key
- name: configure plex repository
  apt_repository:
    filename: plexmediaserver
    repo: 'deb [signed-by=/usr/share/keyrings/PlexSign.key] https://downloads.plex.tv/repo/deb/ public main'
- name: install plex
  apt:
    name: plexmediaserver
- name: create external cache directory to exclude for backups
  file:
    path: /var/cache/plexmediaserver
    state: directory
    owner: plex
    group: plex
    mode: '0700'
- name: create symlink to cache directory
  file:
    src: /var/cache/plexmediaserver
    dest: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Cache'
    state: link
- name: open firewall
  ufw:
    rule: allow
    port: '32400'
    proto: 'tcp'
